import { QuizQuestion } from "./types";

export const quizQuestions: QuizQuestion[] = [
  {
    id: 1,
    type: "radio",
    question: "How many members are in BLACKPINK?",
    choices: ["3", "4", "5", "6"],
    correctIndex: 1,
  },
  {
    id: 2,
    type: "checkbox",
    question: "Which of the following are BLACKPINK members?",
    choices: ["Jennie", "Lisa", "Rose", "Jisoo"],
    correctIndexes: [0, 1, 2, 3],
  },
  {
    id: 3,
    type: "text",
    question: "What year did BLACKPINK debut?",
    correctText: "2016",
  },
  {
    id: 4,
    type: "radio",
    question:
      "Which BLACKPINK song was their first hit to reach #1 on Billboard Hot 100?",
    choices: [
      "DDU-DU DDU-DU",
      "How You Like That",
      "Ice Cream",
      "Lovesick Girls",
    ],
    correctIndex: 2,
  },
  {
    id: 5,
    type: "checkbox",
    question: "Which are BLACKPINK's official colors?",
    choices: ["Black", "Pink", "White", "Purple"],
    correctIndexes: [0, 1],
  },
  {
    id: 6,
    type: "text",
    question: "What is Jennie's full name?",
    correctText: "Jennie Kim",
  },
  {
    id: 7,
    type: "radio",
    question: "Which BLACKPINK member is known as the main dancer?",
    choices: ["Jennie", "Lisa", "Rose", "Jisoo"],
    correctIndex: 1,
  },
  {
    id: 8,
    type: "checkbox",
    question: "Which BLACKPINK songs feature Selena Gomez?",
    choices: ["Ice Cream", "Sour Candy", "Bet You Wanna", "Pretty Savage"],
    correctIndexes: [0, 1],
  },
  {
    id: 9,
    type: "text",
    question: "What is Lisa's nationality?",
    correctText: "Thai",
  },
  {
    id: 10,
    type: "radio",
    question: "Which BLACKPINK member is the oldest?",
    choices: ["Jennie", "Lisa", "Rose", "Jisoo"],
    correctIndex: 3,
  },
  {
    id: 11,
    type: "checkbox",
    question: "Which are BLACKPINK's official positions?",
    choices: ["Main Vocalist", "Main Rapper", "Main Dancer", "Visual"],
    correctIndexes: [0, 1, 2, 3],
  },
  {
    id: 12,
    type: "text",
    question: "What is Rose's real name?",
    correctText: "Roseanne Park",
  },
  {
    id: 13,
    type: "radio",
    question:
      "Which BLACKPINK song has the lyric 'Look at you, now look at me'?",
    choices: [
      "DDU-DU DDU-DU",
      "Kill This Love",
      "How You Like That",
      "Pretty Savage",
    ],
    correctIndex: 0,
  },
  {
    id: 14,
    type: "checkbox",
    question: "Which BLACKPINK members can speak English fluently?",
    choices: ["Jennie", "Lisa", "Rose", "Jisoo"],
    correctIndexes: [0, 1, 2],
  },
  {
    id: 15,
    type: "text",
    question: "What is Jisoo's full name?",
    correctText: "Kim Jisoo",
  },
  {
    id: 16,
    type: "radio",
    question: "Which BLACKPINK song was used in the movie 'Black Widow'?",
    choices: [
      "DDU-DU DDU-DU",
      "Kill This Love",
      "How You Like That",
      "Pretty Savage",
    ],
    correctIndex: 2,
  },
  {
    id: 17,
    type: "checkbox",
    question: "Which BLACKPINK members have solo debuts?",
    choices: ["Jennie", "Lisa", "Rose", "Jisoo"],
    correctIndexes: [0, 1, 2, 3],
  },
  {
    id: 18,
    type: "text",
    question: "What is BLACKPINK's fandom name?",
    correctText: "BLINK",
  },
  {
    id: 19,
    type: "radio",
    question: "Which BLACKPINK member is known as the main vocalist?",
    choices: ["Jennie", "Lisa", "Rose", "Jisoo"],
    correctIndex: 2,
  },
  {
    id: 20,
    type: "checkbox",
    question: "Which BLACKPINK songs have over 1 billion views on YouTube?",
    choices: [
      "DDU-DU DDU-DU",
      "Kill This Love",
      "How You Like That",
      "Boombayah",
    ],
    correctIndexes: [0, 1, 2, 3],
  },
  {
    id: 21,
    type: "text",
    question: "What is Lisa's stage name in Korean?",
    correctText: "리사",
  },
  {
    id: 22,
    type: "radio",
    question: "Which BLACKPINK song features Cardi B?",
    choices: ["Bet You Wanna", "Sour Candy", "Ice Cream", "Pretty Savage"],
    correctIndex: 0,
  },
  {
    id: 23,
    type: "checkbox",
    question: "Which BLACKPINK members were born in 1995?",
    choices: ["Jennie", "Lisa", "Rose", "Jisoo"],
    correctIndexes: [0, 1],
  },
  {
    id: 24,
    type: "text",
    question: "What is BLACKPINK's debut single?",
    correctText: "Boombayah",
  },
  {
    id: 25,
    type: "radio",
    question: "Which BLACKPINK member is known as the visual?",
    choices: ["Jennie", "Lisa", "Rose", "Jisoo"],
    correctIndex: 3,
  },
  {
    id: 26,
    type: "checkbox",
    question:
      "Which BLACKPINK songs are from their first full album 'THE ALBUM'?",
    choices: [
      "How You Like That",
      "Ice Cream",
      "Lovesick Girls",
      "Pretty Savage",
    ],
    correctIndexes: [1, 2, 3],
  },
  {
    id: 27,
    type: "text",
    question: "What is Rose's solo debut song?",
    correctText: "On The Ground",
  },
  {
    id: 28,
    type: "radio",
    question: "Which BLACKPINK member is known as the main rapper?",
    choices: ["Jennie", "Lisa", "Rose", "Jisoo"],
    correctIndex: 0,
  },
  {
    id: 29,
    type: "checkbox",
    question: "Which BLACKPINK members have acting experience?",
    choices: ["Jennie", "Lisa", "Rose", "Jisoo"],
    correctIndexes: [3],
  },
  {
    id: 30,
    type: "text",
    question: "What is BLACKPINK's record label?",
    correctText: "YG Entertainment",
  },
];
